name:
  proj4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - click
  - cycler
  - Flask
  - gunicorn
  - itsdangerous
  - Jinja2
  - joblib
  - kiwisolver
  - MarkupSafe
  - plotly
  - numpy
  - pandas
  - Pillow
  - pyparsing
  - python-dateutil
  - pytz
  - scikit-learn
  - scipy
  - six
  - threadpoolctl
  - Werkzeug
  # - ipykernel
  # - nbformat